import './globals.css'
import type { Metadata } from 'next'
import { Inter, Fira_Code } from 'next/font/google'
import Navbar from './(components)/Navbar'
import Footer from './(components)/Footer'

const inter = Inter({ subsets: ['latin'] })
const firaCode = Fira_Code({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} bg-background`}>
        <div className='max-w-[70%] mx-auto'>
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
